### ISSUE TITLE
Any plans to HI CE 3.0 in Github?

### ISSUE THREAD

**Issue by srbala** [helicalinsight/helicalinsight#12]
I have noticed HI EE 3.0 is available for demos, Any plans to HI CE 3.0 in Github?

**Comment by helicalinsight** [comment]
HI EE 2.1 to HI EE 3.0 the new feature have been primarily on the enterprise side like Adhoc designer, dashboard designer etc. We are planning for a release of CE version also and will be released. Please keep subscribed to know more.
