### ISSUE TITLE
hi ce 2.0.0 build from source guide too simple

### ISSUE THREAD

**Issue by uptonking** [helicalinsight/helicalinsight#2]
Hello, I am interested in your hi as a  big data bi tool.
But I cannot build hi 2.0.0 ce from master branch.
I followed your README.md :
1. create db hice in MySQL
exec the db.sql in */helicalinsight/db-dump/
2. config */helicalinsight/hi-ce/pom.xml at  `production` node
```
systemDirectory  -  */helicalinsight/hi-repository
logLocation
dbUser
dbPassword
```
3.  mvn clean package -Denv=production
4.  copy  */helicalinsight/hi-ce/target/hi-ce.war to tomcat/webapps
5. visit localhost:8080/hice/hi.html or localhost:8080/hice/* 
`HTTP status 404 `
 When I download binary from your website, it's hi 1.0.0, not what I want. 
Where have I made a mistake as above? Can you give me any suggestion for build it myself?

as mention in the [quickstart 2.2](https://helicalinsight.github.io/helicalinsight/#/quickstart)  , there is no `INSTALLATIONPATH\hi-ce\hi-repository` under my */helicalinsight/hi-ce/ directory

is the `INSTALLATIONPATH` my source code path?
when I build from source, 
hi-repository
Third Party Licenses
db-dump
is  in */helicalinsight/
hi-ce.war is in  */helicalinsight/hi-ce/target/

**Comment by helicalinsight** [comment]
As I can see you are trying to access the helical insight application using URL localhost:8080/hice/hi.html 
which is wrong.

Access the application using the URL localhost:8080/hi-ce/hi.html  
Please let me know if you are still facing any problem.
