### ISSUE TITLE
Where can i create the reports?

### ISSUE THREAD

**Issue by liuxiaobing** [helicalinsight/helicalinsight#3]
I have built and deployed the helicalinsight 2.0.0-CE succsesfully. But i cann't find the place to create my reports, just see some guides on the Reports page. Please tell me where can i create the reports. THX.

**Comment by helicalinsight** [comment]
Hi,
Please visit http://www.helicalinsight.com/guide/
Once you are on this page please click on "Technical Guide"

Then you can see a category "Helical Insight Community Edition Usage". 
This category is having a lot of information and tutorials about how to create reports and dashboards using Helical Insight.

Please let me know in case if you are having more questions
