### ISSUE TITLE
support elasticsearch

### ISSUE THREAD

**Issue by xycloud** [helicalinsight/helicalinsight#5]
any plan for support elasticsearch?

**Comment by helicalinsight** [comment]
Helical Insight can be connected to ElasticSearch db using CData jdbc driver for ElasticSearch.

Install CData jdbc driver on your machine and copy the cdata.jdbc.elasticsearch.jar present in lib directory of CData to C:\apache-tomcat-7.0.69\webapps\hi-ce\WEB-INF\lib

NOTE: In your case location of the lib folder may be different based on the Helical Insight hi-ce.war file Deployment, in my case it is depployed in apache tomcat.

Restart the HI-ce application after the cdata.jdbc.elasticsearch.jar file is copied.  

Connection details need to provide in .efwd file are as follows.

<DataSources>
        <Connection id="1" type="sql.jdbc">
            <Driver>cdata.jdbc.elasticsearch.ElasticsearchDriver</Driver>
            <Url>jdbc:elasticsearch:Server=Host Address;Port=Port number of elasticsearch(Default:9200)</Url>
            <User>Username</User>
            <Pass>Password</Pass>
        </Connection>
 </DataSources>
 
Assuming that your elasticsearch has 'customer' index and within that index it has type 'name' Query can be written as  -

<DataMaps>
       <DataMap id="1" connection="1" type="sql" >
           <Name>elasticsample</Name>
            <Query>
                <![CDATA[
       select 
        CData.customer.name.customer_name as name_customer_name 
       from
        CData.customer.name
                ]]>
            </Query>
        </DataMap>  
 </DataMaps>

**Comment by helicalinsight** [comment]
Assuming that your elasticsearch has 'customer' index and within that index it has type 'name' Query can be written as (refer to the notepad file)
[Elasticsearch HI-ce.txt](https://github.com/helicalinsight/helicalinsight/files/1437624/Elasticsearch.HI-ce.txt)
