### ISSUE TITLE
provide a docker image

### ISSUE THREAD

**Issue by xycloud** [helicalinsight/helicalinsight#6]
pls provide a docker image

**Comment by helicalinsight** [comment]
You can currently deploy the current WAR file in your web server. Docker image is in the pipeline and we will update you when we are ready. 

You can refer to this link for more inforamation
https://helicalinsight.github.io/helicalinsight/#/quickstart

**Comment by zeqk** [comment]
@helicalinsight  Any update? Thanks

**Comment by n0nvme** [comment]
Why are you closed this issue? There is still no docker image...
