### ISSUE TITLE
building errors

### ISSUE THREAD

**Issue by greatsxm** [helicalinsight/helicalinsight#7]
**hello all,
    When I followed steps givn to build source code , some errors came to me. Some message like these:**
[WARNING] The POM for com.helicalinsight:hi-vf-plugin:jar:2.0.0.0-CE is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  0.125 s]
[INFO] hi-core ............................................ SUCCESS [  5.733 s]
[INFO] hi-cache ........................................... SUCCESS [  0.713 s]
[INFO] hi-validation ...................................... SUCCESS [  0.630 s]
[INFO] hi-export .......................................... SUCCESS [  0.659 s]
[INFO] hi-externalauth .................................... SUCCESS [  1.072 s]
[INFO] hi-hwf ............................................. SUCCESS [  0.707 s]
[INFO] hi-scheduling ...................................... SUCCESS [  0.769 s]
[INFO] hi-ce .............................................. FAILURE [  0.160 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.795 s
[INFO] Finished at: 2017-10-27T22:14:53+08:00
[INFO] Final Memory: 52M/721M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hi-ce: Could not resolve dependencies for project com.helicalinsight:hi-ce:war:2.0.0.0-CE: Failure to find com.helicalinsight:hi-vf-plugin:jar:2.0.0.0-CE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hi-ce

**Did I miss some steps for building?
Or there is a jar file (maybe a module) which is missed?**

**Comment by helicalinsight** [comment]
Missing jar file has been added. You may download now and it will work fine.
