### ISSUE TITLE
MongoDB in HelicalInsight

### ISSUE THREAD

**Issue by esaiekuitche** [helicalinsight/helicalinsight#8]
Hi all,

How can I configure MongoDB on HelicalInsight on my Linux installation?

I saw one guide on [http://helicalinsight.com/database-support/connect-helical-insight-mongodb/](http://helicalinsight.com/database-support/connect-helical-insight-mongodb/) but it is only for integrating MongoDB on Windows installation of HelicalInsight.

Thank you for your help.

**Comment by helicalinsight** [comment]
Hi.
You might know that we are having two versions one is Community and the other is enterprise. The method which you are following is for enterprise version (but you have downloaded community edition from Github). You can download the enterprise version from website.

Please refer to the below tutorial how to create report using community edition.
http://helicalinsight.com/helical-insight-ce/how-to-create-report-in-helical-insight-ce/

Please visit the below link. 
http://helicalinsight.com/guide/
The above link had a section called "Technical Documentation" with further a category called "Helical Insight Community Edition Usage". You can find a lot of tutorials regarding the usage of community edition over there.

Please let me know in case if you have any other questions.
