### ISSUE TITLE
SQL querry in mongoDB

### ISSUE THREAD

**Issue by esaiekuitche** [helicalinsight/helicalinsight#9]
Hi all,
I'm stating using HelicalInsight for a company,
I'm using commercial version of HelicalInsight to connect to my Mongo Database, 
I able to connect, but I'm not able to get even one column in the collection.
My mongo database name is `scrapy` and the collection in which I want retrieve only the column `news` is feeds.  The result of this query is a table in which all the raw are set to null.

Can someone help me to find the error in this configuration or tell me the way? The guide in the website is not so explicit for me.
Thank you so much @helicalinsight .

inline: {
  version: '1.0',
  defaultSchema: 'mongo',
  schemas: [
    {
      type: 'custom',
      name: 'mongo_raw',
      factory: 'org.apache.calcite.adapter.mongodb.MongoSchemaFactory',
      operand: {
             host: '127.0.0.1:27017',
             database: 'scrapy'
        }
    },
    {
      name: 'feeds',
      tables: [
        {
          name: 'feeds',
          type: 'view',
          sql: 'select cast(_MAP[\'news\'] AS VARCHAR(30)) AS \"news\" \nfrom \"scrapy\".\"feeds\"'
        }		
      ]
    }
  ]
}

**Comment by helicalinsight** [comment]
Hi,
Can you share JSON file and report (folder) which you are creating for connecting so that we can troubleshoot? Also plz share the data as well.
